### ISSUE TITLE
Error de Ortografía: Deberia ser ¿ Como se llamo el primer presidente del Perú?

### ISSUE THREAD

**Issue by JhonCusi** [IsmaelQR/TriviaIsmaelQR#1]
#[](url)
![Screenshot_8](https://user-images.githubusercontent.com/113327569/190881314-e5356c1b-0db1-404f-934d-c2171dc09be6.jpg)

**Comment by IsmaelQR** [comment]
### **ERRORES DE ORTOGRAFICA Y SENTIDO CORREGIDOS**
**En la ultima versión**, se corrigieron errores de sentido y ortográficos.
