### ISSUE TITLE
Error de Puntaje : El puntaje que saque fue -1 y fue multiplicado por 5 = -5 

### ISSUE THREAD

**Issue by JhonCusi** [IsmaelQR/TriviaIsmaelQR#2]
![Screenshot_9](https://user-images.githubusercontent.com/113327569/190881514-d979947c-2cdd-4ec1-8af8-69ec3979e25c.jpg)

**Comment by IsmaelQR** [comment]
### NUEVA FUNCIONALIDAD AÑADIDA
En realidad era parte de la lógica, pero tiene sentido que si se responde bien la pregunta bonus se deba ganar algo. Por ello, si se responde la **pregunta bonus** correctamente y se tiene un puntaje negativo se obtendrá un puntaje de 0.
